# Commit Message Convention
name: 'Commit Message Check'

on:
  push:
    branches: ['*']

jobs:

  check-commit-message:
    name: "check-commit-mesage"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          pattern: '\[(BUGFIX|DOCS|FEATURE|TASK)\] .+$'
          error: 'Your first line has to contain a commit type like "[BUGFIX]".'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}

  unit-test:
    name: "unit-test"
    needs: check-commit-message
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run unit tests
      run: go test -v ./...